language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
 - php build/tools/composer.phar install -o --no-interaction
 - wget -c https://phar.phpunit.de/phpunit.phar
 - chmod +x phpunit.phar

script:
 - php phpunit.phar -c build/

after_script:
 - php vendor/bin/coveralls -v
