language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
 - php build/tools/composer.phar install --prefer-dist -o --no-interaction
 - mkdir build/logs

script:
 - phpunit -c build/

after_script:
 - php vendor/bin/coveralls -v
 - cat build/logs/coveralls-upload.json

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
